size: 2
marsupial_ugv:
  poses0:
    header: ugv0
    seq: 0
    frame_id: ugv
    pose:
      position:
        x: 0.0001
        y: 0.0
        z: 0.0
      orientation:
        x: 0
        y: 0
        z: 0.7068251967430115
        w: 0.7073882818222046
  poses1:
    header: ugv1
    seq: 1
    frame_id: ugv
    pose:
      position:
        x: 0.0001
        y: 0.0
        z: 0.0
      orientation:
        x: 0
        y: 0
        z: 0.7068251967430115
        w: 0.7073882818222046
  poses2:
    header: ugv2
    seq: 2
    frame_id: ugv
    pose:
      position:
        x: 0.0001
        y: 0.0
        z: 0.0
      orientation:
        x: 0
        y: 0
        z: 0.7068251967430115
        w: 0.7073882818222046
  poses3:
    header: ugv3
    seq: 3
    frame_id: ugv
    pose:
      position:
        x: 0.0001
        y: 0.0
        z: 0.0
      orientation:
        x: 0
        y: 0
        z: 0.7068251967430115
        w: 0.7073882818222046
  poses4:
    header: ugv4
    seq: 4
    frame_id: ugv
    pose:
      position:
        x: 0.0001
        y: 0.0
        z: 0.0
      orientation:
        x: 0
        y: 0
        z: 0.7068251967430115
        w: 0.7073882818222046
  size: 5
marsupial_uav:
  poses0:
    header: uav0
    seq: 0
    frame_id: uav
    pose:
      position:
        x: 3.54
        y: 0.0
        z: 3.54
      orientation:
        x: 0
        y: 0
        z: 1
        w: 0
  poses1:
    header: uav1
    seq: 1
    frame_id: uav
    pose:
      position:
        x: 7.07
        y: 0.0
        z: 7.07
      orientation:
        x: 0
        y: 0
        z: 1
        w: 0
  poses2:
    header: uav2
    seq: 2
    frame_id: uav
    pose:
      position:
        x: 10.61
        y: 0.0
        z: 10.61
      orientation:
        x: 0
        y: 0
        z: 1
        w: 0
  poses3:
    header: uav3
    seq: 3
    frame_id: uav
    pose:
      position:
        x: 14.14
        y: 0.0
        z: 14.14
      orientation:
        x: 0
        y: 0
        z: 1
        w: 0
  poses4:
    header: uav4
    seq: 4
    frame_id: uav
    pose:
      position:
        x: 15.14
        y: 0.0
        z: 15.14
      orientation:
        x: 0
        y: 0
        z: 1
        w: 0
  size: 5
tether:
  length0:
    header: tether0
    seq: 0
    frame_id: tether_length
    length: 5.5
  length1:
    header: tether1
    seq: 1
    frame_id: tether_length
    length: 7.5
  length2:
    header: tether2
    seq: 2
    frame_id: tether_length
    length: 7.5
  length3:
    header: tether3
    seq: 3
    frame_id: tether_length
    length: 7.5
  length4:
    header: tether4
    seq: 4
    frame_id: tether_length
    length: 7.5
  size: 5